### ISSUE TITLE
To have tooltip in the ag-grid header

### ISSUE THREAD

**Issue by panthparikh** [Servoy/aggridcomponents#17]
The ag-grid has no tooltip for the headers. If the header is small and if the header title is long then it is pretty hard to read and fit that text. If there is a tooltip then it would be easy to include more columns and the header title can be kept long.

**Comment by tuanway** [comment]
added a headerTooltip property. Will be in next release.

**Comment by nagulapallinaveen** [comment]
Using the below method we can get tooltip on ag-grid header:    
  {
        headerName: 'Policy Number',
        headerTooltip: 'Policy Number'
      },
