### ISSUE TITLE
How to use groupRowRendererFunc in Powergrid

### ISSUE THREAD

**Issue by wvitpr** [Servoy/aggridcomponents#33]
Hi,
Is there a example of how to use groupRowRendererFunc?, I would like to show some additional column information on the grouped row.

**Comment by tp-pitc** [comment]
I am interested in using this - but need more information on the usage. Examples are nice.

**Comment by gboros** [comment]
there is an example in the wiki doc of the property

**Comment by tp-pitc** [comment]
Yes thanks I read all of that.
What it does NOT tell you is that any comments in the function will cause and "unexpected end of input" The stupid code (ag-grid?) recognizes the comment start but not the end. It took ages to figure that one out. Not impressed.

**Comment by seanthomasdevlin** [comment]
Tom, thanks for pointing that out. The code is likely inlined, removing new lines after a comment. Probably best to not send comments for use a comment `/* */` instead of `//`.

I made a note in the docs.
