### ISSUE TITLE
Error after upgrading to release 2.2

### ISSUE THREAD

**Issue by wvitpr** [Servoy/aggridcomponents#35]
I am using the datagrid web component for related line item data extensively im my solution, but since updating to ver 2.2 I am getting the following error

> ERROR org.sablo.BrowserConsole - D9A64A7:2|D830997D-E1C4-4251-A20C-181A067FDE0C|<no-user>|Uncaught TypeError: Cannot read property 'columns' of undefined
> http://localhost:8090/aggrid/groupingtable/groupingtable.js:4323:55
> TypeError: Cannot read property 'columns' of undefined

I can work around it by saving the columnState & restoring manually through an onHide onShow method, but I dont really want to do that everywhere.. on tables that forbid user sorting, grouping etc.

**Comment by wvitpr** [comment]
Hi Gabi,

Can I download this webcomponent and install?





*From:* Gabi <notifications@github.com>
*Sent:* Thursday, 19 September 2019 7:01 PM
*To:* Servoy/aggridcomponents <aggridcomponents@noreply.github.com>
*Cc:* wvitpr <proutley@wvit.com.au>; Author <author@noreply.github.com>
*Subject:* Re: [Servoy/aggridcomponents] Error after upgrading to release
2.2 (#35)



Closed #35 <https://github.com/Servoy/aggridcomponents/issues/35> via
9679d3d
<https://github.com/Servoy/aggridcomponents/commit/9679d3daed4caf831416c18ffc6bf388ff9a9b33>
.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Servoy/aggridcomponents/issues/35?email_source=notifications&email_token=AAAUP7TV3D74YHV4FHZU64TQKM5VNA5CNFSM4IYHYD5KYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOTW43TYA#event-2646194656>,
or mute the thread

**Comment by gboros** [comment]
I did a new release, 2.2.1 that has the fix for this issue

**Comment by wvitpr** [comment]
Thank you !
