### ISSUE TITLE
Add an readonly table option?

### ISSUE THREAD

**Issue by wvitpr** [Servoy/aggridcomponents#37]
Would it be possible to add a option to set the Datagrid to readonly and override all columns edit definitions, or is there a current way of doing this?

**Comment by gboros** [comment]
well, it should be possible with "isEditableDataprovider" from the column, bind it to a global (number or string), and set it to (0/'false'), but I did a quick test, and it seems the data is not updated on the client, and so, the edit state is not changed ...

**Comment by wvitpr** [comment]
Yeah, I tried that, with no luck too

**Comment by gboros** [comment]
try to use for isEditableDataprovider a calculation field, and return the global var in that; btw, the value returned for isEditableDataprovider must be a number (0 non editable, 1 editable)
