### ISSUE TITLE
Add checkbox editType on datagrid

### ISSUE THREAD

**Issue by tonystewart** [Servoy/aggridcomponents#38]
I feel this would be a great addition to the AG grid component.
The current styleClassDataprovider/calculated icon workaround works, but it would be much more efficient to have it as a default feature bound to a field. Thanks for considering this!

**Comment by tonystewart** [comment]
Has there been any update on having CHECKBOX as an editType on AG grids?

**Comment by gboros** [comment]
it is in the backlog https://support.servoy.com/browse/SVY-14487

**Comment by tonystewart** [comment]
Thanks for letting me know.
