### ISSUE TITLE
datagrib in a form extended

### ISSUE THREAD

**Issue by jmlpinaEtec** [Servoy/aggridcomponents#46]
I´m extending a form with a dataGrid with three columns.
![Image01](https://user-images.githubusercontent.com/7591723/78943545-fff1e900-7ab3-11ea-86d7-682358c85e1c.jpg)
In the form extended, I add a new columns in the first position.
![Image02](https://user-images.githubusercontent.com/7591723/78943575-0b451480-7ab4-11ea-93be-c69962a6eed2.jpg)

The new column hides the first column of the principal form and add an empty column.
But if I move the new column to the last position It show the four columns with its data.

![Image03](https://user-images.githubusercontent.com/7591723/78943600-1730d680-7ab4-11ea-896f-6b90f092e372.jpg)

I don´t Know if it´s a bug or if I must to put in the principal form all the columns and in the onLoad event put visible that column

Servoy  2020.3.0

**Comment by gboros** [comment]
You can't change the order of columns in an overridden table (and so, can't have a new column in first position) - this is actually a restriction from Servoy for components with arrays of custom types, in this case the table (component) with the columns (array of custom types). The visibility approach should work.
