### ISSUE TITLE
deleteColumn function doesn't remove column from view.

### ISSUE THREAD

**Issue by MikePogson** [Servoy/aggridcomponents#47]
I am trying to remove a column from the grid on load depending on the user.  Whenever I try to delete a column that a user shouldn't see all the columns seem to get reset and the column is not removed from the view.  The columns array seems correct but the view is not reflecting those changes. 

I tried to remove the column onShow and onLoad and both seem to do the same thing.  Is there something I am missing?

**Comment by tuanway** [comment]
This works fine for me.  Review the attached sample solution.
[testRemoveColumnFromPowerGrid.zip](https://github.com/Servoy/aggridcomponents/files/4505206/testRemoveColumnFromPowerGrid.zip)

**Comment by MikePogson** [comment]
I found the issue, I was operating on the columns array and trying to delete at the same time.  It was causing the array index to jump and missing columns.  Thanks for the help.
