### ISSUE TITLE
Refresh View On Runtime

### ISSUE THREAD

**Issue by juanetec** [Servoy/aggridcomponents#49]
Hi,
I have a Grid that I change the height through the gridOptions when the ColumnStateChanged. 
It works but I have to get out of that forms and return to it.
Does any function for refresh the view when you change the gridOptions?

I sow that in the ag-Grid Documentation:
[https://www.ag-grid.com/javascript-grid-refresh/](url)

Un Saludo

Juan Ramírez

**Comment by gboros** [comment]
I guess you wanted to change the rowHeight property in the gridOptions? Unfortunately some of the properties in gridOptions can't be changed dynamically (see also here https://stackoverflow.com/questions/52428455/dynamically-setting-properties-for-ag-grid), api calls like redrawRows, won't use the new rowHeight set in gridOptions
