### ISSUE TITLE
How to use "getGroupedSelection"

### ISSUE THREAD

**Issue by juanetec** [Servoy/aggridcomponents#51]
Hi,
I am trying to use Grouping Table API "getGroupedSelection" an it give me an error.
when I launch `elements.mygrid.getGroupedSelection()` it return :

> "Error during evaluation:Unexpected: Incorrect return value (0 - not even null/undefined) from client for message (could be due to a close/exit cancelling all pending sync req. to client). Content: []"
> 
 
What I'm doing wrong?

Un Saludo 

Juan Ramírez

**Comment by gboros** [comment]
hi,
this error comes from Servoy core, not the component, I'm not sure what could go wrong in your context, I just tried getGroupedSelection in a simple sample, and it returns an array of records (selected in grouping mode). Can you add a sample to demonstrate the issue?

regards,
Gabi

**Comment by juanetec** [comment]
Sorry Gabi was my fault. I was wrong.
All is correct.

Un Saludo 

Juan Ramírez
