### ISSUE TITLE
Error after upgrading to 2.5.1

### ISSUE THREAD

**Issue by wvitpr** [Servoy/aggridcomponents#53]
Hi,
I am getting the below error after upgrading to 2.5.1 of the NG Grid component
ERROR com.servoy.j2db.util.Debug - TypeError: Cannot read property "formatType" from

2.5.0 is fine.. I cant see any issues my end.. Its a Powergrid btw

**Comment by gboros** [comment]
Hi,
do you have the complete error stack?

**Comment by wvitpr** [comment]
How do I get you that?

**Comment by gboros** [comment]
where you saw the error, is that the all the information, just that line? or can you reproduce this error?

**Comment by wvitpr** [comment]
ERROR com.servoy.j2db.util.Debug - TypeError: Cannot read property
"formatType" from
(C:\Users\prout\Documents\Git_Repo\austubeNG\AustubeERP\forms\sls_project_tbl.js#292)
(Form Context: sls_project_tbl), JSEvent(type = action, source = Component:
<'btn_refresh' of parent FormUI for FormController[form: sls_project_tbl,
fs size:200, selected record:
Record[DATA:Row(db:/austube/sls_projects)[DATA:sls_project_id=184,project_name=AUS35ROUND
Request,project_number=99261,project_value=194.50,project_status=WON,comments=Wait
for tennants-fitout???out of budget,cnt_contact_id=3987,contact_name=Verify
NSW,registed_date=2001-11-28
00:00:00.0,sls_salesrep_id=2,sls_sale_id=0,registed_by=mdome,date_followup=2002-11-28
00:00:00.0,registed_state=null,pursue=null,date_expinvoice=null,is_specified=0,is_concept=0,date_exporder=null,date_expdelivery=null,win_ratepercent=null,prim_salesrep=Milan
Dome,salesrep_concat=null,prim_salesrepstate=NSW,prim_builder=null,prim_contractor=Cavanagh
el,creation_date=null,sls_sale_id_win=null,sec_tenant_id=null,sec_entity_id=null,
CALCULATIONS: {}]]  COLUMS:
sls_project_id,project_name,project_number,project_value,project_status,comments,cnt_contact_id,contact_name,registed_date,sls_salesrep_id,sls_sale_id,registed_by,date_followup,registed_state,pursue,date_expinvoice,is_specified,is_concept,date_exporder,date_expdelivery,win_ratepercent,prim_salesrep,salesrep_concat,prim_salesrepstate,prim_builder,prim_contractor,creation_date,sls_sale_id_win,sec_tenant_id,sec_entity_id,getChangedData,getDataSource,getException,revertChanges,isEditing,save,getPKs,isNew,hasChangedData,rollbackChanges,isRelatedFoundSetLoaded,getFoundset,deleteRecord,,destroyed:false]>,
formName = sls_project_tbl, elementName = btn_refresh, timestamp =
2020-07-13 22:18:28.998,modifiers = 0,x =2403,y = 70,data = null)

       at
*C:\Users\prout\Documents\Git_Repo\austubeNG\AustubeERP\forms\sls_project_tbl.js*:292
(onAction_search)

       at
*C:\Users\prout\Documents\Git_Repo\austubeNG\AustubeERP\forms\sls_project_tbl.js*:197
(loadProjects)

       at
*C:\Users\prout\Documents\Git_Repo\austubeNG\AustubeERP\forms\sls_project_tbl.js*:189
(loadTables)

       at
*C:\Users\prout\Documents\Git_Repo\austubeNG\AustubeERP\forms\sls_project_tbl.js*:119
(btn_refresh)

org.mozilla.javascript.EcmaError: TypeError: Cannot read property
"formatType" from
(C:\Users\prout\Documents\Git_Repo\austubeNG\AustubeERP\forms\sls_project_tbl.js#292)

       at
*org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java*:4224)
~[org.eclipse.dltk.javascript.rhino_2020.3.0.3562.jar:?]

       at
*org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java*:4202)
~[org.eclipse.dltk.javascript.rhino_2020.3.0.3562.jar:?]

       at
*org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java*:4235)
~[org.eclipse.dltk.javascript.rhino_2020.3.0.3562.jar:?]

       at
*org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java*:4254)
~[org.eclipse.dltk.javascript.rhino_2020.3.0.3562.jar:?]

       at
*org.mozilla.javascript.ScriptRuntime.undefReadError(ScriptRuntime.java*:4266)
~[org.eclipse.dltk.javascript.rhino_2020.3.0.3562.jar:?]

       at
*org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java*:1548)
~[org.eclipse.dltk.javascript.rhino_2020.3.0.3562.jar:?]

       at org.mozilla.javascript.gen.c_7._c_anonymous_7(Unknown Source)
~[?:?]

       at org.mozilla.javascript.gen.c_7.call(Unknown Source) ~[?:?]

       at
*com.servoy.j2db.server.ngclient.component.RuntimeWebComponent$4.call(RuntimeWebComponent.java*:355)
~[?:?]

       at
*org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java*:1487)
~[org.eclipse.dltk.javascript.rhino_2020.3.0.3562.jar:?]

       at *org.mozilla.javascript.Interpreter.interpret(Interpreter.java*:815)
~[org.eclipse.dltk.javascript.rhino_2020.3.0.3562.jar:?]

       at
*org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java*:109)
~[org.eclipse.dltk.javascript.rhino_2020.3.0.3562.jar:?]

       at
*org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java*:399)
~[org.eclipse.dltk.javascript.rhino_2020.3.0.3562.jar:?]

       at
*org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java*:3534)
~[org.eclipse.dltk.javascript.rhino_2020.3.0.3562.jar:?]

       at
*org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java*:107)
~[org.eclipse.dltk.javascript.rhino_2020.3.0.3562.jar:?]

       at
*com.servoy.j2db.scripting.ScriptEngine.executeFunction(ScriptEngine.java*:670)
[servoy_shared_2020.3.0.3562.jar:?]

       at
*com.servoy.j2db.debug.RemoteDebugScriptEngine.executeFunction(RemoteDebugScriptEngine.java*:393)
[servoy_debug_2020.3.0.3562.jar:?]

       at
*com.servoy.j2db.server.ngclient.component.EventExecutor.executeEvent(EventExecutor.java*:234)
[servoy_ngclient_2020.3.0.3562.jar:?]

       at
*com.servoy.j2db.server.ngclient.DataAdapterList.executeEvent(DataAdapterList.java*:126)
[servoy_ngclient_2020.3.0.3562.jar:?]

       at
*com.servoy.j2db.server.ngclient.WebFormComponent$FormcomponentEventHandler.executeEvent(WebFormComponent.java*:240)
[servoy_ngclient_2020.3.0.3562.jar:?]

       at *org.sablo.BaseWebObject.doExecuteEvent(BaseWebObject.java*:335)
[sablo_2020.3.0.3562.jar:?]

       at *org.sablo.BaseWebObject.executeEvent(BaseWebObject.java*:324)
[sablo_2020.3.0.3562.jar:?]

       at
*org.sablo.services.server.FormServiceHandler.executeEvent(FormServiceHandler.java*:137)
[sablo_2020.3.0.3562.jar:?]

       at
*com.servoy.j2db.server.ngclient.NGFormServiceHandler.executeEvent(NGFormServiceHandler.java*:503)
[servoy_ngclient_2020.3.0.3562.jar:?]

       at
*org.sablo.services.server.FormServiceHandler.executeMethod(FormServiceHandler.java*:84)
[sablo_2020.3.0.3562.jar:?]

       at
*com.servoy.j2db.server.ngclient.NGFormServiceHandler.executeMethod(NGFormServiceHandler.java*:482)
[servoy_ngclient_2020.3.0.3562.jar:?]

       at
*org.sablo.websocket.WebsocketEndpoint$5.run(WebsocketEndpoint.java*:408)
[sablo_2020.3.0.3562.jar:?]

       at *org.sablo.eventthread.Event$1.run(Event.java*:102)
[sablo_2020.3.0.3562.jar:?]

       at
*org.sablo.websocket.CurrentWindow.runForWindow(CurrentWindow.java*:76)
[sablo_2020.3.0.3562.jar:?]

       at *org.sablo.eventthread.Event.execute(Event.java*:92)
[sablo_2020.3.0.3562.jar:?]

       at
*org.sablo.eventthread.EventDispatcher.dispatch(EventDispatcher.java*:125)
[sablo_2020.3.0.3562.jar:?]

       at *org.sablo.eventthread.EventDispatcher.run(EventDispatcher.java*:89)
[sablo_2020.3.0.3562.jar:?]

       at
*com.servoy.j2db.server.ngclient.eventthread.NGEventDispatcher.run(NGEventDispatcher.java*:55)
[servoy_ngclient_2020.3.0.3562.jar:?]

       at java.lang.Thread.run(Unknown Source) [?:?]





*From:* Gabi <notifications@github.com>
*Sent:* Monday, 13 July 2020 9:30 PM
*To:* Servoy/aggridcomponents <aggridcomponents@noreply.github.com>
*Cc:* wvitpr <proutley@wvit.com.au>; Author <author@noreply.github.com>
*Subject:* Re: [Servoy/aggridcomponents] Error after upgrading to 2.5.1
(#53)



where you saw the error, is that the all the information, just that line?
or can you reproduce this error?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Servoy/aggridcomponents/issues/53#issuecomment-657503446>,
or unsubscribe

**Comment by gboros** [comment]
hm, is it possible that the dataset you're setting to the grid, has a columnName that does not have a corresponding column with that columnName as dataprovider in the powergrid?

**Comment by wvitpr** [comment]
I just double checked, and it all looks fine. Even just reverting t0 2.5.0
fixes the error and the data displays correctly, so it seems to be
associated to 2.5.1



*From:* Gabi <notifications@github.com>
*Sent:* Monday, 13 July 2020 11:25 PM
*To:* Servoy/aggridcomponents <aggridcomponents@noreply.github.com>
*Cc:* wvitpr <proutley@wvit.com.au>; Author <author@noreply.github.com>
*Subject:* Re: [Servoy/aggridcomponents] Error after upgrading to 2.5.1
(#53)



hm, is it possible that the dataset you're setting to the grid, has a
columnName that does not have a corresponding column with that columnName
as dataprovider in the powergrid?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Servoy/aggridcomponents/issues/53#issuecomment-657558989>,
or unsubscribe

**Comment by gboros** [comment]
can you check with the latest source code? now we skip the date formating on column from the dataset that are not used in the grid

**Comment by wvitpr** [comment]
I just tried it.. works perfectly.. thank you.



*From:* Gabi <notifications@github.com>
*Sent:* Tuesday, 14 July 2020 4:33 PM
*To:* Servoy/aggridcomponents <aggridcomponents@noreply.github.com>
*Cc:* wvitpr <proutley@wvit.com.au>; Author <author@noreply.github.com>
*Subject:* Re: [Servoy/aggridcomponents] Error after upgrading to 2.5.1
(#53)



can you check with the latest source code? now we skip the date formating
on column from the dataset that are not used in the grid

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Servoy/aggridcomponents/issues/53#issuecomment-657997038>,
or unsubscribe
