### ISSUE TITLE
How can I delete a Group on a table: RuntimeWebComponent<aggrid-groupingtable_abs>?

### ISSUE THREAD

**Issue by juanetec** [Servoy/aggridcomponents#55]
Hi, 
I am trying to delete a group on runtime.
What I am doing is getting the ColumnState and changing the property rowGroupIndex to null,
but it does not work.

This is the code that I am using:

`
function delGrouping(){
	var  /** @type {RuntimeWebComponent<aggrid-groupingtable_abs>} */ _aggrid  = elements.table;
	var _state = _aggrid.getColumnState();
	
		_state = sn_gridStateCleanGrouping(_state);
		if (_state){
			_aggrid.restoreColumnState(_state);
		}
		
	
}'
'
function sn_gridStateCleanGrouping(_state){
	var /** @type {Object<*>} */ _jsonState = JSON.parse(_state);
	if (!_jsonState || !_jsonState.columnState || !_jsonState.columnState.length) return null;
	
	for (var i = 0; i < _jsonState.columnState.length; i++) {
		if (_jsonState.columnState[i].rowGroupIndex!=null) _jsonState.columnState[i].rowGroupIndex=null;
	}
	return  JSON.stringify(_jsonState);
}`

What I am doing wrong?

Un Saludo 

Juan Ramírez

**Comment by gboros** [comment]
hi,
you need to remove the column from rowGroupColumnsState, so doing _jsonState.rowGroupColumnsState = []; will remove all grouping

**Comment by juanetec** [comment]
Hi Gabi,
I try what you had said, but it does not work.
What I am doing wrong?

This is the code that I use:
`function delGrouping(){
	var  /** @type {RuntimeWebComponent<aggrid-groupingtable_abs>} */ _aggrid  = elements.table;
	var _state = _aggrid.getColumnState();
	
		_state = sn_gridStateCleanGrouping(_state);
		if (_state){
			_aggrid.restoreColumnState(_state);
		}
		
	
}`

`function sn_gridStateCleanGrouping(_state){
	var /** @type {Object<*>} */ _jsonState = JSON.parse(_state);
	if (!_jsonState || !_jsonState.columnState || !_jsonState.columnState.length) return null;
	 _jsonState.rowGroupColumnsState = [];
	return  JSON.stringify(_jsonState);
}`

At the attacked file is a solution example.

[gridsWorkshop.zip](https://github.com/Servoy/aggridcomponents/files/4917824/gridsWorkshop.zip)

Un Saludo 

Juan Ramírez

**Comment by gboros** [comment]
hi,
you need to do also what you have done at the beginning, setting rowGroupIndex = null for all columns, so the clean grouping function should look like this:

`function sn_gridStateCleanGrouping(_state){
	var /** @type {Object<*>} */ _jsonState = JSON.parse(_state);
	if (!_jsonState || !_jsonState.columnState || !_jsonState.columnState.length) return null;
	for (var i = 0; i < _jsonState.columnState.length; i++) {
		if (_jsonState.columnState[i].rowGroupIndex!=null) _jsonState.columnState[i].rowGroupIndex=null;
	}
	_jsonState.rowGroupColumnsState = [];
	return  JSON.stringify(_jsonState);
}`

**Comment by juanetec** [comment]
Ok, now.

Thanks

Un Saludo

Juan Ramírez
