### ISSUE TITLE
Multiple row selection change when the selection is more then 100 record aprox.

### ISSUE THREAD

**Issue by juanetec** [Servoy/aggridcomponents#56]
Hi,
in a aggrid Table using the multiple row selection, when I select less than 100 row aprox.  
it work perfect, but if I try to scroll down the list to select more rows, unselect a group of then from the first selection.

Un Saludo

Juan Ramírez

**Comment by gboros** [comment]
created support case https://support.servoy.com/browse/SVY-15209
