### ISSUE TITLE
AG Grid not sorting on calculated fields

### ISSUE THREAD

**Issue by panthparikh** [Servoy/aggridcomponents#6]
I am using  the AG Grid component and the sorting is not working correctly on the calculated fields. I have even checked the Servoy Admin Logs and was not able to see any error over there. The only error which I am able to get is in the console which says "**sort column promise resolved**". Please let me know if I am doing something wrong here. I am attaching the screenshot of the calculated field and it can seen where 50LB BAG is between the BULK .

![screenshot](https://user-images.githubusercontent.com/33933932/33177591-2d648b5c-d031-11e7-96c5-46e1633c0d59.png)

Regards Panth

**Comment by paronne** [comment]
Hi,

sorting on calculated fields is not possible indeed. The sorting is applied to the foundset, is therefore resolved with a database query, which indeed is not possible to perfom on calculated fields.

Regards,
Paolo

**Comment by seanthomasdevlin** [comment]
Could it perhaps be possible to provide a custom comparator function in the future to hand calculations ?
Similar to JSFoundSet.sort(myFunc)
