### ISSUE TITLE
cannot read property '0' of undefined

### ISSUE THREAD

**Issue by Himani-ship-it** [Servoy/aggridcomponents#60]
![Bug](https://user-images.githubusercontent.com/57792994/93809146-8e28e880-fc6a-11ea-9608-578a29dab803.png)

Line 31 is giving me the said error. Why is the said element said to be undefined? And why is it not being read?

**Comment by jcompagner** [comment]
Which file is that exactly?
Can you reproduce this with a sample?

**Comment by Himani-ship-it** [comment]
> Which file is that exactly?
> Can you reproduce this with a sample?

This is a JavaScript file, I was trying to do cellular automaton. I'm sorry I forgot to mention that earlier. 
The code does not show error until I make a new grid called next, and assign grid the values of next, and call the draw function again.  
Grid is a matrix of randomly assigned 1s and 0s.

**Comment by gboros** [comment]
why do you think this is an issue in the grid component? from the code snippet it does not seem any grid function to be involved

**Comment by Himani-ship-it** [comment]
`function make2Darray (cols, rows){
    let arr = new Array(cols);
    for(let i= 0; i< arr.length; i++){
        arr[i] = new Array(rows);
    }
    return arr;
}
let next;
let grid;
let cols = 30;
let rows = 30;

function setup() {
    createCanvas(20*cols,20*rows);
    background(255);
    stroke(255);
    next = make2Darray(cols, rows);
    grid = make2Darray(cols, rows);
    for (let i=0; i< cols; i++){
        for(let j=0; j< rows; j++){
            grid[i][j] = Math.round(Math.random());
        }
    } 
}

function draw() {
    for (let i=0; i< cols; i++){
        for(let j=0; j< rows; j++){
            let x = i*20;
            let y = j*20;
            if(grid[i][j] === 1){
                fill(0);
                rect(x,y,20,20);              
            }      
        }
    }
}

function ruleSet() {

    for(let i =0; i<cols; i++){
        for(let j=1; j<rows; j++){
            let front = grid[i][j-1];
            let back = grid[i][j+1];
            let current = grid[i][j];
            let newState = next[i][j];

            if(front ==0 && current ==0 && back ==0 ){
                newState = 0;
            }
            else if(front ==0 && current ==0 && back ==1 ){
                newState = 1;
            }
            else if(front ==0 && current ==1 && back ==0 ){
                newState = 0;
            }
            else if(front ==0 && current ==1 && back ==1 ){
                newState = 1;
            }
            else if(front ==1 && current ==0 && back ==0 ){
                newState = 0;
            }
            else if(front ==1 && current ==0 && back ==1 ){
                newState = 1;
            }
            else if(front ==1 && current ==1 && back ==0 ){
                newState = 1;
            }
            else if(front ==1 && current ==1 && back ==1 ){
                newState = 1;
            }
         } 
    }
}

while (true) {
    grid = next;
    draw();
}

`

This is the entire code. The debugger says issue is with line 31 from the snippet. I'm not sure if by property 0 it means grid[0][0]. If it does, I don't understand why it's not able to read.

**Comment by Himani-ship-it** [comment]
`function make2Darray (cols, rows){
let arr = new Array(cols);
for(let i= 0; i< arr.length; i++){
arr[i] = new Array(rows);
}
return arr;
}
let next;
let grid;
let cols = 30;
let rows = 30;

function setup() {
createCanvas(20cols,20rows);
background(255);
stroke(255);
next = make2Darray(cols, rows);
grid = make2Darray(cols, rows);
for (let i=0; i< cols; i++){
for(let j=0; j< rows; j++){
grid[i][j] = Math.round(Math.random());
}
}
}

function draw() {
for (let i=0; i< cols; i++){
for(let j=0; j< rows; j++){
let x = i20;
let y = j20;
if(grid[i][j] === 1){
fill(0);
rect(x,y,20,20);
}
}
}
}

function ruleSet() {

for(let i =0; i<cols; i++){
    for(let j=1; j<rows; j++){
        let front = grid[i][j-1];
        let back = grid[i][j+1];
        let current = grid[i][j];
        let newState = next[i][j];

        if(front ==0 && current ==0 && back ==0 ){
            newState = 0;
        }
        else if(front ==0 && current ==0 && back ==1 ){
            newState = 1;
        }
        else if(front ==0 && current ==1 && back ==0 ){
            newState = 0;
        }
        else if(front ==0 && current ==1 && back ==1 ){
            newState = 1;
        }
        else if(front ==1 && current ==0 && back ==0 ){
            newState = 0;
        }
        else if(front ==1 && current ==0 && back ==1 ){
            newState = 1;
        }
        else if(front ==1 && current ==1 && back ==0 ){
            newState = 1;
        }
        else if(front ==1 && current ==1 && back ==1 ){
            newState = 1;
        }
     } 
}
}

while (true) {
grid = next;
draw();
}

`

This is the entire code. The debugger says issue is with line 31 from the snippet. I'm not sure if by property 0 it means grid[0][0]. If it does, I don't understand why it's not able to read.

**Comment by gboros** [comment]
Are you sure you're reporting the issue to the right project? as I still don't get what the code has to do with Servoy's NG Grid component. there is not any NG Grid related api call in the code snippet; also functions like createCanvas, stroke, backround seems odd related to NG Grids

**Comment by paronne** [comment]
Hi, if you are not sure on which project to report this issue, can you make a file export of the .servoy solution and attach it so we may suggest on which project it relates.
