### ISSUE TITLE
ngGrids and Sub Forms

### ISSUE THREAD

**Issue by wvitpr** [Servoy/aggridcomponents#63]
Hi Guys,
Should it be possible to have a subform with a grid inherited from the parent, then make changes to columns on the subform grid like hide etc ? I am getting an -unresolved(dataprovider) on the subform grid.. oddly it still displays the data ok though.

**Comment by gboros** [comment]
hi,
that should work just fine; that (unresolved) could be just a display issue in the developer - you could create a case on Servoy's support for that, with a sample solution or workspace export.
