### ISSUE TITLE
getColumnState() returning null Sometimes

### ISSUE THREAD

**Issue by wvitpr** [Servoy/aggridcomponents#64]
Version 2.6.2
When I first load datagrid the function getColumnState() returns null until you change the column state, then it works..

**Comment by gboros** [comment]
where/when do you call getColumnState? the grid needs to be rendered already (onready of the grid called), so calling during onshow of the form is too early. do you use restoreColumnState before getColumnState? is onColumnDataChange never called on first show of the grid?

**Comment by gboros** [comment]
pleas have a look if this commit fixes the issue for you

**Comment by wvitpr** [comment]
Yes, I was loading the restoreColumnState() before it was ready, but what is the best way to use the 0nReady() function.. ? for this purpose.

**Comment by gboros** [comment]
onReady is called when the ag grid we use under the hood, is setup, and all its api can be used; you should use this when calling api's that are related to the table UI, that NG Grids forward or rely on ag grid api.
