### ISSUE TITLE
Formatting of footer text

### ISSUE THREAD

**Issue by SteveHawes** [Servoy/aggridcomponents#65]
I have a data grid with a numeric column that has a format of '¤#.00' to show it as a currency value. I have added an aggregate to the table that is the sum of this column and show that total in the footer of the data grid. All is good so far and the total shows. The problem I have is that I cannot find a way to format the footer value as a currency and it shows as a plain number with a varying number of decimal places according to the current amount. (See images)

How can I format the footer as a currency value and if this is not possible can I request that this be added as a feature?

Thanks.

![image](https://user-images.githubusercontent.com/23415735/98542698-30d40f80-2289-11eb-9d6a-5f0d0cfe275b.png)

![image](https://user-images.githubusercontent.com/23415735/98542712-37fb1d80-2289-11eb-943b-42cce7ce569c.png)

**Comment by gboros** [comment]
the footerText dataprovider will be converted to a string (and will not use the format of the column) - this is a limitation of aggrid - it converts any footer data to text, so nggrids can't apply the formating.
a workaround could be to use a calculation that returns the desired already formated string.
