### ISSUE TITLE
PowerGrid the ag-Grid-AutoColumn how can I set properties?

### ISSUE THREAD

**Issue by juanetec** [Servoy/aggridcomponents#66]
Hi,
using the Power Grid and if for example 1 column is grouping and the 'ag-Grid-AutoColumn' appear. 
I move the width of this group column.
I store the state of the grid and to apply this state later.
If I come back to this grid and restored the column state the width does not keep the with I gave it before.
There is any trick to solve this situation?
Or doing that by process maybe can I put the  'ag-Grid-AutoColumn'  pinned left?

Un Saludo

Juan Ramírez

**Comment by paronne** [comment]
Hi Juan,

columns will auto resize by default to fit the grid width.
If you don't want a column to be auto resized you can set the column property autoResize=false.

Regards,
Paolo

**Comment by juanetec** [comment]
Hi Paolo,
yes I know that property but my question is haw can I control the grouping column (it call 'ag-Grid-AutoColumn').
In my case I try to show some statistics and when I refresh the information the first column become small.
![Image 2](https://user-images.githubusercontent.com/26114868/104893336-33c73c80-596b-11eb-9475-39638c771ac0.png)
![Image 4](https://user-images.githubusercontent.com/26114868/104893356-39248700-596b-11eb-875b-7959c6ae28bb.png)

I have a process to change the size and the pinned I works but not the  autoResize=false.
`function onColumnStateChanged(columnState) {
	var  _state,/** @type {Object<*>} */ _jsonState,_restore=false;
	_state= _super.onColumnStateChanged(columnState);
	if (_state){
		_jsonState = JSON.parse(_state);
		 if (!_jsonState || !_jsonState.columnState || !_jsonState.columnState.length) return _state; 
		 for (var i = 0; i < _jsonState.columnState.length; i++) {
			 if ( _jsonState.columnState[i].colId=='ag-Grid-AutoColumn'&& !_jsonState.columnState[i].pinned){
				 _jsonState.columnState[i].pinned='left';
				 _jsonState.columnState[i].width=200;
				 _jsonState.columnState[i].autoResize=false;
				 _restore=true;
				 break;
			 }
		 }
	}
	if (_jsonState && _restore){
		_state = JSON.stringify(_jsonState);
		elements.rejilla.restoreColumnState(_state);
	}
	return _state;
}`

Un Saludo

Juan

**Comment by paronne** [comment]
Hi Juan,

you mean to use the entire row for the grouped row ?
There is a property for that. You can add it in the gridOptions as groupUseEntireRow:true.

Let me know if that is what you are looking for

**Comment by juanetec** [comment]
Hi Paolo, 
no this is not what I am looking for.
Sorry is difficult to explain it.

I have in a form a powerGrid, I feed that powerGrid with a function and I launch that process with a button.
This function depends on some variables.
With the svyProperties module I store the columnState.
Some columns are pinned to the left and sometimes you want to group some of that columns.
When you have the powerGrid with a column grouped, you have a new column, 
this column if you check it inside, it have the id = 'ag-Grid-AutoColumn'. But I cannot put properties to this column. And I cannot store the properties, so I do a process to change that properties.
The problem is that when I launch the procees to feed the powerGrid again the width of this column became to small.
All the columns have the property  autoResize=false.

![Image 6](https://user-images.githubusercontent.com/26114868/104941950-b07a0b00-59ab-11eb-9076-dacd5f9223db.png)
![Image 10](https://user-images.githubusercontent.com/26114868/104941953-b112a180-59ab-11eb-986e-8db20ab8aeb1.png)


Un saludo

Juan ramírez

**Comment by paronne** [comment]
Hi Juan,

i understand your problem now.
AutoGroup column are defined in the gridOptions property, using the autoGroupColumnDef property.
You can possibly override the column def using the ngService:

```
	plugins.ngPowerGrid.gridOptions = {
        autoGroupColumnDef : {
        	headerName: "Group Title",
			minWidth: 200,
			suppressSizeToFit: true
		}
	}
```

However be aware by doing so you will override the built in implementation of autoGroupColumnDef  for the power grid.
Specifically you won't be able to use the groupStyleClass property and the groupRowRendererFunc property.

Regards,
Paolo

**Comment by juanetec** [comment]
Thanks that's is what I want. 
Sorry my bad explanation.

Un Saludo

Juan Ramírez
