### ISSUE TITLE
 Error in _aggrid.restoreColumnState(_value); 2.6.3 Version

### ISSUE THREAD

**Issue by juanetec** [Servoy/aggridcomponents#68]
Hi,
I use  scopes.svyProperties to store the gridState, and it work good. 
But when I change an id of a column from the grid or  create a new column and the gridstate stored is apply  with _aggrid.restoreColumnState(_value);   jumps that Errors:

`ERROR org.sablo.BrowserConsole - 8E4D2A3:2|198EC1D5-37B9-436E-B688-83655CE4C2CB|jramirez|Cannot restore columns state, different number of columns in saved state and component
ERROR org.sablo.BrowserConsole - 6C682FB:2|60940804-27AB-411E-BD6D-F7D5164E95C0|jramirez|Cannot restore columns state, cant find column from state in component columns
`

And reset the gridState with all the columns at the original state. 
That is really annoying to our client that has his own grid configuration.

Is there any trick to control that?
I the previous version it did not happen.

Un Saludo

Juan Ramírez

**Comment by gboros** [comment]
can't you save the columns state as soon as you change a column id or add a new column, so you always have a valid up-do-date state saved?

**Comment by juanetec** [comment]
Hi Gari,
The problem is when I add a new column in developer and I send to the production environment.
The scopes.svyProperties has a store grid state with for example 10 columns an the new solution has 11 columns.
So when It try to restore the grid jump the error and reset the grid state.

In this case the final client has this grid before that shows 3 columns of the 10 columns (the another 7 are with the enableToolPanel in false) after this update it shows the 11 columns with the enableToolPanel to true.

Un Saludo

**Comment by paronne** [comment]
Hi Juan,

adding new columns into the grid while a previous state was stored already is always tricky.
Eventually the grid should be able to notify the user that something has changed; if a column has been added/removed as user i would like to know that something has changed.
I am wondering if you are able to "control" the state before calling the restore. 
If you set an id for all your columns, before applying the restore you can compare your stored state vs the actual columns (elements.table.columns).
You can then decide what to do, e.g. yuo can add yourself the new columns to the state object to be restored.
Note carefully something like this may work only if you set an unique id for all your columns, otherwise you won't be able to identify the column state vs the actual column in elements.table.column.

**Comment by jcompagner** [comment]
i also wonder how this could work, a simple 1 like adding a column at the end, could maybe work.
But what about if you had 10 columns
you remove column 5 8
and add 3 new columns at position 2 4 9

what then?

**Comment by juanetec** [comment]
Hi Paolo and Johan,
I will try what Paolo said. 
I can check the stored state compared the ID if in case of new column I can add on the JSON and if I have deleted some column I have to deleted from the JSON. 
At the end I have  to have the same number of columns and the same ID betewen the state I want to store en the grid.

Un Saludo 

Juan Ramírez

**Comment by juanetec** [comment]
Hi, 
I have done the function to control that and it works.


function snProppertiesGridStateApplyCheck(_value,_aggrid){
	var /** @type {JSON} */ _jsonstate,/** @type {Array<CustomType<aggrid-groupingtable.column>>} */ _columns=[],
	/** @type {CustomType<aggrid-groupingtable.column>} */ _column,_arrayColumnState = [],_arrayColumnStateTemp = [],_arrayIdDelete=[],_encontrada=false,
	/** @type {{aggFunc,colId,hide,pinned,pivotIndex,rowGroupIndex,width}} */ _columnStateObj={},i,j,_jsonChange=false;
	if (!_value || !_aggrid) return _value;
	_jsonstate = JSON.parse(_value);
	_arrayColumnState = _jsonstate['columnState'];
	_columns = _aggrid.columns;
	for ( i = 0; i < _columns.length; i++) {
		_column = _columns[i];
		_encontrada=false;
		for (j = 0; j < _arrayColumnState.length; j++) {
			if (_arrayColumnState[j].colId.indexOf('_svy')==-1 && _arrayColumnState[j].colId==_column.id){
				_encontrada=true;
			}
		}
		if (!_encontrada){
			_columnStateObj={};
			_columnStateObj.colId = _column.id;
			_columnStateObj.hide = false;
			_columnStateObj.width = 100;
			_arrayColumnStateTemp.push(_columnStateObj);
		}
	}
	//Add
	if (_arrayColumnStateTemp && _arrayColumnStateTemp.length){
		_arrayColumnState = _arrayColumnState.concat(_arrayColumnStateTemp);
		_jsonChange=true;
	}
	
	for (j = 0; j < _arrayColumnState.length; j++) {
		if (_arrayColumnState[j].colId.indexOf('_svy')==-1){
			_encontrada=false;
			
			for ( i = 0; i < _columns.length; i++) {
				_column = _columns[i];
				if (_arrayColumnState[j].colId==_column.id) _encontrada=true;
			}
			if (!_encontrada){
				_arrayIdDelete.push(_arrayColumnState[j].colId);
			}
		}
	}
	//Delete
	for ( i = 0; i < _arrayIdDelete.length; i++) {
		for (j = _arrayColumnState.length-1; j >= 0; j--){
			if (_arrayColumnState[j].colId==_arrayIdDelete[i]){
				_arrayColumnState.splice(j,1);
			}
		}
		_jsonChange=true;
	}
	if (_jsonChange){
		_jsonstate['columnState'] = _arrayColumnState;
		_value = JSON.stringify(_jsonstate);
	}
	
	return _value;
}`

thanks

Un Saludo

Juan Ramírez
