### ISSUE TITLE
Feature Request: Enable/Disable Sorting & Menu

### ISSUE THREAD

**Issue by ErosN** [Servoy/aggridcomponents#7]
We would like to add the ability to enable or disable sorting and the menu column on specific columns. Since it's currently not possible to sort on Calculated Columns, we would like to completely remove the ability of the user to click on the column header to sort the column. 

Also, we would like the ability to hide the menu button on a specific column (so that they do not see the grouping option).

**Comment by paronne** [comment]
It will be done.
