### ISSUE TITLE
Delete All Columns in PowerGrid

### ISSUE THREAD

**Issue by wvitpr** [Servoy/aggridcomponents#70]
Hello,
Whats the best way to delete columns from powerGrid? I am trying to use below with no success. I have noticed there is a deleteAllColumns in datagrid, which would be very handy in powergrid.

var _columns = elements.datasettable_1.columns;
for (var i = 0; i < _columns.length; i++) {
     elements.datasettable_1.deleteColumn(_columns[i].id)
}

**Comment by gboros** [comment]
the _columns.length is changed each time you delete a column inside the loop; try this code instead:

	for (;_columns.length > 0;) {
		elements.datasettable_1.deleteColumn(_columns[0].id)
	}
