### ISSUE TITLE
Removing row group Item Count from Powergrid

### ISSUE THREAD

**Issue by wvitpr** [Servoy/aggridcomponents#74]
There is an option to remove the Count from grouped rows in Datagrid, could we have that in power grid too please, in the meantime how do I modify or not show, as you can see from below its not very useful in this use case.
![image](https://user-images.githubusercontent.com/83966/146894073-4d76befd-8953-44b5-8742-183830d710c6.png)

**Comment by gboros** [comment]
you can remove that using CSS, add this to your stylesheet:
.ag-group-child-count {
	display: none;	
}

**Comment by wvitpr** [comment]
Perfect, thank you..
