### ISSUE TITLE
There is no way to programatically set the selection of a grouped dataGrid

### ISSUE THREAD

**Issue by swingman** [Servoy/aggridcomponents#89]
You can select the rows of a grouped dataGrid and get the current selection using

getGroupedSelection()

But there is no equivalent to restore a selection. There is no

setGroupedSelection(pks)

Would it be possible to add this?

**Comment by gboros** [comment]
what is the use case for you for setGroupedSelection? do you want to restore a selection previously saved, or do you want to set the selection in grouping mode, when switching from non-grouping to groping, to the selection you have in non-grouping?

**Comment by swingman** [comment]
It is to restore a previous selection. You can select the records in the foundset of a form. but you can’t make the grid reflect this selection when it is grouped.

C

On 21 Dec 2022, at 10:42, Gabi ***@***.***> wrote:



what is the use case for you for setGroupedSelection? do you want to restore a selection previously saved, or do you want to set the selection in grouping mode, when switching from non-grouping to groping, to the selection you have in non-grouping?

**Comment by jcompagner** [comment]
so in other words you see a grid that has a a few records shown (of the thousands)
and the first record is selected (which is also our default selection)

then when you group you expect that the record that was selected (could be just the first one that is default, not really a user selection) must stay selected?
even if that is in a group that is the 234 group, and in that group that first record is now on index 345 ?
we need to really scroll to that group, find that record and select that record that was selected?

Are you then willing to accept that we need to query ALL the data of ALL the groups until we find that selection?
How do you see that?

For me if you sort or find/search or group, the selection should always go back to what is then the first record.
We just can't do much more.. everything else will have a huge performance impact to try to keep that selection..

Yes you can really also have a user selection (so it really selected lets say record index 23) and then it does the group, but the same thing applies here.. what do you really expect? do you really expect that servoy will try to find (load all the data per group, every group is a foundset by itself) to try to find the record (pk)  of that selection that we had before?

**Comment by p-bakker** [comment]
Think this is about 'selected'records in AGGrid, meaning selected by checkbox, so not the 'active record' in a foundset (called the selectedRecord in Servoy)

This is a very valid use-case: user selects a few record while the grid is grouped, moves to another form, back: selection gone

In our own version of the AGGrid component we made the selection persist between hiding and showing the form that has the grid on it, but that was a LOT of very tricky work, basically tracking selected pk's (of fully selected groups when you allow checkboxes on the groups to select all the descendants) and then auto-selecting rows with matching PK's when they get (lazy) loaded etc etc

**Comment by jcompagner** [comment]
right but that is a bit different, there you move back to the same data (so its kind of loaded already)
that i can understand..

But if you sort, or group or find/search then you really change the data.. and it suddenly can be anything..
groups change, order is changing...

**Comment by paronne** [comment]
For multi-selection in gruping can use an actual dataprovider with a checkbox editType. Can possibly a calculation with no body that you can use to flag selected records. 
Only exception, that won't cover the selection of a whole group ( can select single lines only with a dataprovider + chexkbox )
Enable foundset selection/multi-select in grouping mode is tricky because the record you see in groups are not truly the same records you have in your form's foundset ( you may have only 200 records in foundset while group are showing records which can be at position 140.567 of your form's foundset ); 
A user selecting a line in a group, should not force a selection also in the form's foundset because finding ( and selecting ) that record can be extremely expensive.

**Comment by swingman** [comment]
In my case we rarely have more than 400 records.
The User has grouped the grid and has some record selected as they are working down the list. I store the PK so I can re-select in the foundset later.
Then they jump to another project, the grid gets loaded with data from that project, then they jump back to the first project and I load the original list into the grid and I want to show the correct record selected  in the grid, so the use can keep working down the list. I’d like to tell the grid to select one or more records by their pk.

A reload is acceptable in my scenario as I’m already having to reload…

C

On 21 Dec 2022, at 12:08, Johan Compagner ***@***.***> wrote:



so in other words you see a grid that has a a few records shown (of the thousands)
and the first record is selected (which is also our default selection)

then when you group you expect that the record that was selected (could be just the first one that is default, not really a user selection) must stay selected?
even if that is in a group that is the 234 group, and in that group that first record is now on index 345 ?
we need to really scroll to that group, find that record and select that record that was selected?

Are you then willing to accept that we need to query ALL the data of ALL the groups until we find that selection?
How do you see that?

For me if you sort or find/search or group, the selection should always go back to what is then the first record.
We just can't do much more.. everything else will have a huge performance impact to try to keep that selection..

Yes you can really also have a user selection (so it really selected lets say record index 23) and then it does the group, but the same thing applies here.. what do you really expect? do you really expect that servoy will try to find (load all the data per group, every group is a foundset by itself) to try to find the record (pk) of that selection that we had before?

**Comment by jcompagner** [comment]
but you also restore the groups then through code?
so you remember the groups for that user for that view
and then that view can change with different data and if it restores to the previous data you also restore the groups and then you also want to restore the selection?
